### ISSUE TITLE
working example

### ISSUE THREAD

**Issue by brettmc** [jerowork/aura-router-nested-middleware#1]
Hi!
I'm after some help in trying to get a working example running (at which point I was hoping to submit a documentation PR).
This uses zend\diactoros to create a request, and I'm intending that it will a 'hello world' response with a "foo: bar" header, but I suspect I'm not using middleware and request handlers correctly...

```php
<?php
require 'vendor/autoload.php';
use Aura\Router\RouterContainer;
use Jerowork\AuraRouterNestedMiddleware\AuraRouterNestedMiddleware;
use Jerowork\AuraRouterNestedMiddleware\MiddlewarePipe\StratigilityMiddlewarePipe;
use Psr\Http\Message\ServerRequestInterface;
use Interop\Http\Server\RequestHandlerInterface;
use Interop\Http\Server\MiddlewareInterface;
use Zend\Stratigility\MiddlewarePipe;
use Zend\Diactoros\ServerRequest;
use Zend\Diactoros\Uri;
use Zend\Diactoros\Response;

class HomeAction implements MiddlewareInterface
{
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler)
    {
        $response = $handler->handle($request);
        $response->getBody()->write('Hello world!');
        return $response;
    }
}

class FooMiddleware implements MiddlewareInterface
{
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler)
    {
        $response = $handler->handle($request);
        return $response->withHeader('foo', 'bar');
    }
}

class DefaultHandler implements RequestHandlerInterface
{
    public function handle(ServerRequestInterface $request)
    {
        return new Response();
    }
}

$router = new RouterContainer();
$middleware = new AuraRouterNestedMiddleware(
    $router,
    new StratigilityMiddlewarePipe(new MiddlewarePipe())
);
$map = $router->getMap();

$map->get('home', '/', [
    new FooMiddleware(),
    new HomeAction(),
]);

$matcher = $router->getMatcher();

$request = (new ServerRequest())->withUri(new Uri('/'))->withMethod('GET');
$response = $middleware->process($request, new DefaultHandler());
var_dump($response);
```

**Comment by jerowork** [comment]
Hi Brett!

I have figured out why your example didn't work. I have fixed a duplicate use of a variable. This resulted in a new 0.2.1 release.

Important to know, since Stratigility 2.1 you have to define explicitly the version of http-interop/http-middleware you want to use (and thereby the use of the methods handle() vs process() in your middleware). This because Zend Stratigility (which is used internally in the middleware class) depends on it:

> http-interop/http-middleware, which provides the interfaces that will become PSR-15. In Stratigility 1.3, this is pinned to the 0.2 series; in Stratigility 2.0, this is pinned to 0.4.1+. Since Stratigility 2.1 you have to explicitly define an http-interop/http-middleware dependency in your composer.json, and you can use any version which is currently supported by the polyfill package webimpress/http-middleware-compatibility.

**Comment by brettmc** [comment]
thank you very much, that example is working now. I'll keep playing around as I find time...
